/**
 * Rental Finder 26 — independent Nottinghamshire source registry.
 *
 * One entry represents one letting organisation, not one branch. The runtime
 * reports whether each source is actually working, empty, blocked, or broken.
 * We use ordinary GET requests only and do not bypass anti-bot controls.
 */
export const SOURCES = [
  {
    id: "fhp-living",
    label: "FHP Living",
    type: "page",
    url: "https://fhpliving.co.uk/rent/",
    detailPathPattern: "^/properties/",
    maxDetails: 12,
    enabled: true,
  },
  {
    id: "robert-ellis",
    label: "Robert Ellis",
    type: "page",
    url: "https://www.robertellis.co.uk/properties/to-rent/",
    detailPathPattern: "^/property-to-rent/",
    maxDetails: 14,
    enabled: true,
  },
  {
    id: "granger-oaks",
    label: "Granger & Oaks",
    type: "page",
    url: "https://grangerandoaks.co.uk/property_search_results/loc-all/prop-all/minp-0/maxp-0/bath-0/bed-0/type-tolet/sort-price/",
    detailPathPattern: "^/property/",
    maxDetails: 14,
    enabled: true,
  },
  {
    id: "city-lettings",
    label: "City Lettings Nottingham",
    type: "page",
    url: "https://static.citylettingsuk.com/lettings-search-nottingham.php",
    detailPathPattern: "(lettings|property|details)",
    maxDetails: 12,
    enabled: true,
  },
  {
    id: "truelove-lettings",
    label: "Truelove Property Lettings",
    type: "page",
    url: "https://www.truelovelettings.co.uk/rentals/city-lets",
    detailPathPattern: "^/rentals/",
    maxDetails: 12,
    enabled: true,
  },
  {
    id: "wellington-lettings",
    label: "Wellington Lettings",
    type: "page",
    url: "https://www.wellingtonlettings.co.uk/residential-lettings",
    detailPathPattern: "(property|details|residential)",
    maxDetails: 12,
    enabled: true,
  },
  {
    id: "cp-walker",
    label: "CP Walker & Son",
    type: "page",
    url: "https://www.cpwalker.co.uk/nottinghamshire/lettings/",
    detailPathPattern: "(property|lettings|to-rent)",
    maxDetails: 10,
    enabled: true,
  },
  {
    id: "walton-allen",
    label: "Walton & Allen",
    type: "page",
    url: "https://www.waltonandallen.co.uk/properties-to-rent/",
    detailPathPattern: "(property|properties-to-rent)",
    maxDetails: 10,
    enabled: true,
  },
  {
    id: "holden-copley",
    label: "HoldenCopley",
    type: "page",
    url: "https://www.holdencopley.co.uk/property-to-rent-in-nottingham/",
    detailPathPattern: "(property|to-rent)",
    maxDetails: 10,
    enabled: true,
  },
  {
    id: "hammond-property-services",
    label: "Hammond Property Services",
    type: "page",
    url: "https://www.hammondpropertyservices.com/property-search/for-letting/in-nottinghamshire/",
    detailPathPattern: "(property|letting)",
    maxDetails: 10,
    enabled: true,
  },
  {
    id: "richard-watkinson",
    label: "Richard Watkinson & Partners",
    type: "page",
    url: "https://www.richardwatkinson.co.uk/properties/lettings",
    detailPathPattern: "^/properties/.+/lettings$|^/properties/[0-9]+/lettings$|^/properties/",
    maxDetails: 10,
    enabled: true,
  },
  {
    id: "places2nest",
    label: "Places2Nest",
    type: "page",
    url: "https://places2nest.co.uk/",
    detailPathPattern: "(property|rent)",
    maxDetails: 8,
    enabled: true,
  },
  {
    id: "alasdair-morrison",
    label: "Alasdair Morrison Lettings",
    type: "page",
    url: "https://www.amorrison.co.uk/properties-to-let",
    detailPathPattern: "^/properties-to-let/property/",
    maxDetails: 12,
    enabled: true,
  },

];
